version: 1.0
provider:
  name: openfaas
functions:
  call-name:
    lang: python3-flask
    handler: ./call-name
    image: ${DOCKER_USERNAME}/chatbot-functions-call-name:latest
  git-webhook-alert:
    lang: python3-http
    handler: ./git-webhook-alert
    image: git-webhook-alert:latest

