name: dev ci-cd
on:
  workflow_dispatch: {}
  push:
    branches: 
      - dev
jobs:
  func-build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Define ENV VARS
        id: define_env
        run:  echo "::set-output name=github-sha-short::$(echo $GITHUB_SHA | cut -c 1-7)"
      -
        name: Pull template
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: template store pull python3-flask
      - 
        name: Run build
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: build -f stack.yml --shrinkwrap
      -
        name: Login to OpenFaaS Gateway
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: login -p ${{ secrets.OPENFAAS_GATEWAY_PASSWORD }} \
                      -g ${{ secrets.OPENFAAS_GATEWAY }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Build and Push the OpenFaaS function
        uses: docker/build-push-action@v2
        with:
          context: ./build/call-name/
          file: ./build/call-name/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/chatbot-functions-call-name:latest-${{ steps.define_env.outputs.github-sha-short }}
      - 
        name: Deploy the function
        uses: docker://openfaas/faas-cli:latest-root
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        with:
          args: deploy -f stack.yml --tag sha --gateway ${{ secrets.OPENFAAS_GATEWAY }}
